portfolio/urls.py
#from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/',include('projects.urls')),
    path('',include('users.urls')),
    
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password_reset_sent/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
# from portfolio.projects.views import createProject
from projects import views
app_name ='projects'
urlpatterns=[
    path('',views.projects,name='projects'),
    path('project/<str:pk>/',views.project, name = 'project'),
    path('create-project/',views.createProject,name='create-project'),
    path('update-project/<str:pk>/',views.updateProject,name='update-project'),
    path('delete-project/<str:pk>/',views.deleteProject,name='delete-project'),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('',views.profiles, name='all-profile'),  
    path('single-profile/<str:pk>/',views.profile, name='single-profile'), 
    path('login/',views.loginUser, name='login'),
    path('logout/',views.logoutUser,name='logout'),
    path('register/',views.registerUser, name='register'),
    path('account/',views.userAccount, name='account'),
    path('edit/',views.editAccount, name='edit'),
    path('create-skill/',views.createSkill,name='create-skill'),
    path('update-skill/<str:pk>/',views.updateSkill,name='update-skill'),
    path('delete-skill/<str:pk>/',views.deleteSkill,name='delete-skill'),
    
    path('inbox/',views.inbox, name='inbox'),
    path('view-message/<str:pk>/',views.viewMessage,name='view-message'),
    path('create-message/<str:pk>/',views.createMessage,name='create-message'),
]

projects/models.py
from distutils.command.upload import upload
from email.mime import image
from django.db import models
from users.models import Profile

# Create your models here.
class Project(models.Model):
    project_type = [
        ('static','static application'),
        ('dynamic', 'web application')
    ]
    owner = models.ForeignKey(Profile,on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null = True, blank = True)
    image = models.ImageField(upload_to = 'photos/', default = 'photos/website.jpg', null = True, blank = True)
    demo_link =  models.CharField(max_length=2000, null = True, blank = True)
    source_link =  models.CharField(max_length=2000, null = True, blank = True)
    tags = models.ManyToManyField('Tag',blank=True)
    created = models.DateTimeField(auto_now_add=True)
    vote_total = models.IntegerField(default=0, null= True, blank= True)
    vote_ratio = models.IntegerField(default=0, null= True, blank= True)
    type = models.CharField(max_length=2000,choices= project_type, null = True, blank = True)
    
    def __str__(self):
        return str(self.title)
    
    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upvotes = reviews.filter(value='up').count()
        totalCount = reviews.count()
        voteRatio = (upvotes/totalCount)*100
        
        self.vote_total = totalCount
        self.vote_ratio = voteRatio
        self.save()
        
    def reviewers(self):
        reviewers = self.review_set.all().values_list('owner_id',flat=True)
        return reviewers
    
class Review(models.Model):
    
    values = [('up','Like'),('down','Dislike')]
    owner = models.ForeignKey(Profile,on_delete=models.CASCADE,null=True,blank=True)
    project = models.ForeignKey(Project,on_delete=models.CASCADE,null=True,blank=True)
    body = models.TextField(null=True,blank=True)
    value = models.CharField(max_length=20,choices=values)
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.value
    class Meta:
        unique_together = [['owner', 'project']]

class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

users/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200)
    username = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    profile_image = models.ImageField(upload_to='profiles', default='profiles/default.jpg', null=True, blank=True)
    short_intro = models.CharField(max_length=2000, null=True, blank=True)
    bio = models.TextField( null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    social_github = models.CharField(max_length=2000, null=True, blank=True)
    social_twitter = models.CharField(max_length=2000, null=True, blank=True)
    social_youtube = models.CharField(max_length=2000, null=True, blank=True)
    social_linkedin = models.CharField(max_length=2000, null=True, blank=True)
    social_website = models.CharField(max_length=2000, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)

class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(Profile,on_delete=models.SET_NULL, null=True, blank=True, related_name='messages')
    name = models.CharField(max_length=200,null=True,blank=True)
    email = models.EmailField(max_length=200,null=True,blank=True)
    subject = models.CharField(max_length=200,null=True,blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.subject
    
    class Meta:
        ordering = ['is_read','-created']

def createProfile(sender, instance, created, **kwargs):
    userobj = instance
    if created:
        profile = Profile.objects.create(
            user = userobj,
            name = userobj.username,
            username = userobj.username,
            email = userobj.email
        )

users/forms.py
from .models import Message, Profile, Skill
from pyexpat import model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name','email','username','password1','password2']
        labels = {
            'first_name':'Name',
        }
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs)

        for label,field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = [ 'name','username','email','profile_image','short_intro','bio', 'location',
                  'social_github','social_twitter','social_youtube','social_linkedin','social_website']
        
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs)

        for label,field in self.fields.items():
            field.widget.attrs.update({'class':'input'})
    
class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = '__all__'
        exclude = ['owner']
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs)

        for label,field in self.fields.items():
            field.widget.attrs.update({'class':'input'})

class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']
    
    def __init__(self, *args, **kwargs): 
        super().__init__(*args, **kwargs)

        for label,field in self.fields.items():
            field.widget.attrs.update({'class':'input input--text', 'placeholder':'Enter value'})

users/views.py
from email import message
from django.shortcuts import redirect, render
from django.contrib import messages
from .forms import CustomUserCreationForm, ProfileForm, SkillForm, MessageForm
from .models import Message, Profile, Skill
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .utils import searchProfiles, paginateProfiles
from django.db.models import Q
# Create your views here.

def profiles(request):
    profiles = searchProfiles(request)
    page_profiles, paginator = paginateProfiles(request, profiles,3)
    context = {
        'profiles':profiles,
        'paginator': paginator,
    }
    return render(request, 'users/all-profiles.html',context)

def profile(request,pk):
    profile = Profile.objects.get(id=pk)
    
    topSkill = profile.skill_set.exclude(description = '')
    otherSkill = profile.skill_set.filter(description = '')
    
    context = {
        'profile':profile,
        'topSkill':topSkill,
        'otherSkill':otherSkill,
    }
    return render(request, 'users/single-profile.html',context)

def loginUser(request):
    
    page = 'login'
    if request.user.is_authenticated:
        return redirect('projects:projects')
    
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request,'User does not exist')
            # print('User does not exist')
        
        user = authenticate(username=username,password=password)
        
        if user is not None:
            login(request,user)
            messages.success(request,'User logged in')
            return redirect(request.GET['next'] if 'next' in request.GET else 'users:account')
        else:
            messages.error(request,'Username or password does not match')
            #print('Username or password does not match')
    context = {}
    
    return render(request, 'users/login_register.html',context)

def logoutUser(request):
    logout(request)
    messages.success(request,'User logged out')
    return redirect('users:login')

def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request,'User created successfully')
            return redirect('users:login')
        else:
            messages.error(request,"Some error occured")
    context = {'page':page,'form':form}
    return render(request,'users/login_register.html',context)

@login_required(login_url='users:login')
def userAccount(request):
    profile = request.user.profile
    context = {'profile':profile}
    return render(request,'users/account.html', context)

@login_required(login_url='users:login')
def editAccount(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        form.save()
        messages.success(request,'Profile updated successfully')
        return redirect('users:account')
        
    context = {'form':form}
    return render(request,'users/edit-profile.html', context)


@login_required(login_url='users:login')
def createSkill(request):
    profile = request.user.profile
    form = SkillForm()
    if request.method == 'POST':
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner = profile
            skill.save()
            messages.success(request,'Skill created successfully')
            return redirect('users:account')
        else:
            messages.error(request,'Some error occured')
    context = {'form':form,}
    return render(request,'users/skill-form.html',context)

@login_required(login_url='users:login')
def updateSkill(request,pk):
    profile = request.user.profile
    skillobj = profile.skill_set.get(id=pk)
    form = SkillForm(instance=skillobj)
    if request.method == 'POST':
        form = SkillForm(request.POST, instance=skillobj)
        if form.is_valid():
            form.save()
            messages.success(request,'Skill updated successfully')
            return redirect('users:account')
        else:
            messages.error(request,'Some error occured')
    context = {'form':form,}
    return render(request,'users/skill-form.html',context)

@login_required(login_url='users:login')
def deleteSkill(request,pk):
    profile = request.user.profile
    skillobj = profile.skill_set.get(id=pk)
    if request.method == 'POST':
        skillobj.delete()
        messages.success(request,'Skill deleted successfully')
        return redirect('users:account')
    
    context = {'object':skillobj,}
    return render(request,'delete.html',context)

@login_required(login_url='users:login')
def inbox(request):
    recipient = request.user.profile
    received_msgs = recipient.messages.all
    unreadCount = received_msgs.filter(is_read=False).count()
        
    context = {'received_msgs':received_msgs, 'unreadCount':unreadCount}
    return render(request,'users/inbox.html',context)

@login_required(login_url='users:login')
def viewMessage(request,pk):
    message = Message.objects.get(id=pk)

    if message.is_read == False:
        message.is_read == True
        message.save()
        
    context = {'message':message,}
    return render(request,'users/message.html',context)

def createMessage(request,pk):
    recipient = Profile.objects.get(id=pk)
    form = MessageForm()
    
    if request.method == 'POST':
        form = MessageForm(request.POST)
        try:
            sender = request.user.profile
        except:
            sender = None
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.recipient = recipient
            
            if sender:
                message.name = sender.name
                message.email = sender.email
            
            message.save()
            return redirect('users:all-profile')

    context = {'form': form, 'recipient': recipient}
    return render(request, 'users/message-form.html',context)
    

users/templates/users/account.html
{% extends 'main.html' %}

{% block content %}
  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:edit' %}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">Based in {{profile.location}}</p>
              <ul class="dev__social">
                {% if profile.social_github %}
                <li>
                  <a title="Github" href="" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}              
                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="#" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}
                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="#" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}
                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="#" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'users:create-skill' %}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
            {% for skill in profile.skill_set.all %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{skill}}</h4>
                <p>
                  {{skill.description}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:update-skill' skill.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'users:delete-skill' skill.id %}?next=/account/"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}
            
          </table>

          <div class="settings">
           
            <h3 class="settings__title">Projects</h3>
            {% csrf_token %}
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'projects:create-project'%}"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">
            {% for project in profile.project_set.all %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'projects:project' project.id %}"><img src="{{project.image.url}}" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'projects:project' project.id %}">{{project.title}}</a>
                <p>
                  {{project.description|slice:"200"}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'projects:update-project' project.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'projects:delete-project' project.id %}?next=/account/"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}
           
          </table>
        </div>
      </div>
    </div>
  </main>
  {% endblock %}

users/templates/users/all-profiles.html
{% extends 'main.html' %}
{% block content %}


 <!-- Main Section -->
 <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="search_query"
                placeholder="Search by developer name" value="{{request.GET.search_query}}"/>
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">

            {% for profile in profiles %}

          <div class="column card">
            <div class="dev">
              <a href="{% url 'users:single-profile' profile.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{profile.profile_image.url}}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{profile.name}}</h3>
                    <h5>{{profile.short_intro|slice:"50"}}</h5>
                  </div>
                </div>
                <p class="dev__info">
                    {{profile.bio|slice:"300"}}
                </p>
                <div class="dev__skills">

                    {% for skill in profile.skill_set.all %}

                  <span class="tag tag--pill tag--main">
                    <small>{{skill}}</small>
                  </span>
                  {% endfor %}
                </div>
              </a>
            </div>
          </div>
                    
          {% endfor %}

        </div>
      </div>
    </section>
    {% if profiles.has_other_pages %}
    <div class="pagination">
      <ul class="container">
        {% if profiles.has_previous %}
        <li><a href="?page={{profiles.previous_page_number}}&search_query={{request.GET.search_query}}" class="btn">&#10094; Prev</a></li>
        {% else %}
        <li><a href="" class="btn btn--disabled">&#10094; Prev</a></li>
        {% endif %}

        {% for page in paginator.page.page_range %}
        {% if page == profiles.number %}
        <li><a href="?page={{page}}&search_query={{request.GET.search_query}}" class="btn btn--sub">{{page}}</a></li>
        {% else %}
        <li><a href="?page={{page}}&search_query={{request.GET.search_query}}" class="btn">{{page}}</a></li>
        {% endif %}
        {% endfor %}

        {% if profiles.has_naxt %}
        <li><a href="?page={{profiles.next_page_number}}&search_query={{request.GET.search_query}}" class="btn">Next &#10095;</a></li>
        {% else %}
        <li><a href="" class="btn btn--disabled">&#10095; Next</a></li>
        {% endif %}
      </ul>
    </div>
    {% endif %}
  </main>

{% endblock %}

users/templates/users/login_register.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

{% if page == 'register' %}

<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{% static 'images/icon.svg' %}" alt="icon" />
      </a>
      <h3>Account SignUp</h3>
      <p>Create a new developer account</p>
    </div>

    <form action="{% url 'users:register' %}" method="POST" class="form auth__form">
      {% csrf_token %}
      {% for field in form %}
      <!-- Input:Text -->
      <div class="form__field">
        <label for="formInput#text">{{field.label}}</label>
        {{field}}
       {% for error in field.errors %}
       <p style="color: red;">{{error}}</p>
       
       {% endfor %}
      </div>
      {% endfor %}
     
      <div class="auth__actions">
        <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
      </div>
    </form>
    <div class="auth__alternative">
      <p>Already have an Account?</p>
      <a href="{% url 'users:login' %}">Log In</a>
    </div>
  </div>
</div>

{% else %}

<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{%static 'images/icon.svg'%}" alt="icon" />
        </a>
        <h3>Account Login</h3>
        <p>Hello Developer, Welcome Back!</p>
      </div>

      <form action="#" method='POST' class="form auth__form">
        {% csrf_token %}
        <!-- Input:Email -->
        <div class="form__field">
          <label for="formInput#text">Username: </label>
          <input
            class="input input--text"
            id="formInput#text"
            type="text"
            name="username"
            placeholder="Enter your username..."
          />
        </div>

        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#password">Password: </label>
          <input
            class="input input--password"
            id="formInput#passowrd"
            type="password"
            name="password"
            placeholder="••••••••"
          />
        </div>
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
          <a href="{% url 'password_reset' %}">Forgot Password?</a>
        </div>
      </form>
      <div class="auth__alternative">
        <p>Don’t have an Account?</p>
        <a href="{% url 'users:register' %}">Sign Up</a>
      </div>
    </div>
  </div>
{% endif %}
{% endblock %}

users/templates/users/message.html
{% extends 'main.html' %}
{% block content %}
<main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{% url 'users:inbox' %}"><i class="im im-angle-left"></i></a>
        <h2 class="message__subject">{{message.subject}}</h4>
          {% if message.sender %}
          <a href="{% url 'users:single-profile' message.sender.id %}" class="message__author">{{message.name}}</a>
          {% else %}
          {{message.name}}
          {% endif %}
          <p class="message__date">May 31, 2021, 04:37 PM</p>
          <div class="message__body">
           {{message.body|linebreaksbr}}
          </div>
      </div>
    </div>
  </main>
  {% endblock  %}

users/templates/users/single-profile.html
{% extends 'main.html'%}
{% block content %}

<!-- Main Section -->
  <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">Based in {{profile.location}}</p>
              <ul class="dev__social">
                  {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}

                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}

                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}

                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>                
                {% endif %}

              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
              {% for skill in topSkill %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{skill.name}}</h4>
                <p class="devSkill__info">
                  {{skill.description}}
                </p>
              </div>
              {% endfor %}
              
              
              <h3 class="devInfo__subtitle">Other Skills</h3>
              
              <div class="devInfo__otherSkills">

                {% for skill in otherSkill %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{skill.name}}</small>
                </span>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

              {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{%url 'projects:project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{project.image.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href="{% url 'users:single-profile' project.owner.id %}">By {{project.owner.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}</span> Postitive
                        Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:'s'}})
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                        {%endfor%}
                        </span>
                      </div>
                    </div>
                  </a>
                </div>
              </div>
                  {%endfor%}    

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock %}