portfolio/urls.py
#from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/',include('projects.urls')),
    path('',include('users.urls')),
    
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('password_reset_sent/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path
# from portfolio.projects.views import createProject
from projects import views
app_name ='projects'
urlpatterns=[
    path('',views.projects,name='projects'),
    path('project/<str:pk>/',views.project, name = 'project'),
    path('create-project/',views.createProject,name='create-project'),
    path('update-project/<str:pk>/',views.updateProject,name='update-project'),
    path('delete-project/<str:pk>/',views.deleteProject,name='delete-project'),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('',views.profiles, name='all-profile'),  
    path('single-profile/<str:pk>/',views.profile, name='single-profile'), 
    path('login/',views.loginUser, name='login'),
    path('logout/',views.logoutUser,name='logout'),
    path('register/',views.registerUser, name='register'),
    path('account/',views.userAccount, name='account'),
    path('edit/',views.editAccount, name='edit'),
    path('create-skill/',views.createSkill,name='create-skill'),
    path('update-skill/<str:pk>/',views.updateSkill,name='update-skill'),
    path('delete-skill/<str:pk>/',views.deleteSkill,name='delete-skill'),
    
    path('inbox/',views.inbox, name='inbox'),
    path('view-message/<str:pk>/',views.viewMessage,name='view-message'),
    path('create-message/<str:pk>/',views.createMessage,name='create-message'),
]

templates/delete.html
{% extends 'main.html' %}

{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">    
            <a class="backButton" href="{% url 'users:account' %}"><i class="im im-angle-left"></i></a>  
            <form action="" class="form" method="POST">
                <!-- Input:Text -->
                {% csrf_token %}
                <p>
                    Are you sure that you want to delete {{object}}?                                   
                </p>                
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Delete" />
                <a class="btn btn--sub btn--lg  my-md"  href="{{request.GET.next}}">Cancel</a>
            </form>
</form>
{% endblock %}

templates/form-template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <!-- Icon - IconMonster -->
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="uikit/styles/uikit.css" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="styles/app.css" />

    <title>DevSearch - Connect with Developers!</title>
</head>

<body>
    <!-- Header Section -->
    <header class="header">
        <div class="container container--narrow">
            <a href="/" class="header__logo">
                <img src="images/logo.svg" alt="DevSearch Logo" />
            </a>
            <nav class="header__nav">
                <input type="checkbox" id="responsive-menu" />
                <label for="responsive-menu" class="toggle-menu">
                    <span>Menu</span>
                    <div class="toggle-menu__lines"></div>
                </label>
                <ul class="header__menu">
                    <li class="header__menuItem"><a href="index.html">Developers</a></li>
                    <li class="header__menuItem"><a href="projects.html">Projects</a></li>
                    <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
                    <li class="header__menuItem"><a href="account.html">My Account</a></li>
                    <li class="header__menuItem"><a href="login.html" class="btn btn--sub">Login/Sign Up</a></li>
                </ul>
            </nav>
        </div>
    </header>

    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="#"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST">
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Text Field: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter text" />
                    </div>

                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Text Field: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter text" />
                    </div>

                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">Text Field: </label>
                        <input class="input input--text" id="formInput#text" type="text" name="text"
                            placeholder="Enter text" />
                    </div>
                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
</body>

</html>

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      
        <!-- Favicon -->
        <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
        <!-- Icon - IconMonster -->
        <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
        <!-- Mumble UI -->
        <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
        <!-- Dev Search UI -->
        <link rel="stylesheet" href="{% static 'styles/app.css' %}" />
      
        <title>DevSearch - Connect with Developers!</title>
      </head>

<body>
    <h1>Logo-Title</h1>
    {%include 'nav-bar.html'%}
    {% if messages %}
    {% for message in messages %}
    <div id="message-div" class="alert alert--{{message.tags}}">
        <p class="alert__message">{{message}}</p>
        <button onclick="closebutton()" class="alert__close">x</button>

    </div>

    {% endfor %}
    {% endif %}
    <hr>
        {% block content %}



        {% endblock %}
    <hr>
<script src="{% static 'js/proj.js' %}"> </script>
</body>
</html>

templates/nav-bar.html
{% load static %}

<header class="header">
    <div class="container container--narrow">
      <a href="/" class="header__logo">
        <img src="{% static 'images/logo.svg' %}" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="{% url 'users:all-profile' %}">Developers</a></li>
          <li class="header__menuItem"><a href="{% url 'projects:projects' %}">Projects</a></li>
          
          {% if request.user.is_authenticated %}
          <li class="header__menuItem"><a href="{% url 'users:inbox' %}">Inbox</a></li>
          <li class="header__menuItem"><a href="{% url 'projects:create-project' %}">Add Project</a></li>
          <li class="header__menuItem"><a href="{% url 'users:account' %}">My Account</a></li>
          
          <li class="header__menuItem"><a href="{% url 'users:logout' %}" class="btn btn--sub">Logout</a></li>
          {% else %}
          <li class="header__menuItem"><a href="{% url 'users:login' %}" class="btn btn--sub">Login/Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </header>

templates/password_reset.html
{% extends 'main.html' %}
{% block content %}
<style>
input.input[type='text'],
input.input[type='email'],
input.input[type='password'],
input.input[type='number'],
select.input,
textarea.input {
  min-width: 24rem;
  width: 100%;
  padding: 1.2rem 1.5rem;
  border-radius: 0.5rem;
  border: 2px solid var(--color-light);
  transition: all 0.3s ease-in-out;
  background-color: var(--color-bg);
}

input.input[type='text']:focus,
input.input[type='email']:focus,
input.input[type='password']:focus,
input.input[type='number']:focus,
input.input[type='text']:active,
input.input[type='email']:active,
input.input[type='password']:active,
input.input[type='number']:active{
  outline: none;
  border: 2px solid var(--color-main);
}
</style>

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>Password reset</h3>

            <p>Forgotten your password? Enter your email address below, and
                we'll email instructions for setting a new one.</p>
            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                {{form.as_p}}       
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Reset my password" />
            </form>
        </div>
    </div>
</main>

{% endblock  %}

templates/password_reset_complete.html
{% extends 'main.html' %}
{% block content %}
<style>
input.input[type='text'],
input.input[type='email'],
input.input[type='password'],
input.input[type='number'],
select.input,
textarea.input {
  min-width: 24rem;
  width: 100%;
  padding: 1.2rem 1.5rem;
  border-radius: 0.5rem;
  border: 2px solid var(--color-light);
  transition: all 0.3s ease-in-out;
  background-color: var(--color-bg);
}

input.input[type='text']:focus,
input.input[type='email']:focus,
input.input[type='password']:focus,
input.input[type='number']:focus,
input.input[type='text']:active,
input.input[type='email']:active,
input.input[type='password']:active,
input.input[type='number']:active{
  outline: none;
  border: 2px solid var(--color-main);
}
</style>

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>Password reset complete</h3>

            <p>
                Your password has been set. You may go ahead and login now.
            </p>
            <br>
                
            <a class="btn btn--sub btn--lg  my-md" href="{% url 'users:login' %}">Login</a>
           
        </div>
    </div>
</main>

{% endblock  %}

templates/password_reset_confirm.html
{% extends 'main.html' %}
{% block content %}
<style>
input.input[type='text'],
input.input[type='email'],
input.input[type='password'],
input.input[type='number'],
select.input,
textarea.input {
  min-width: 24rem;
  width: 100%;
  padding: 1.2rem 1.5rem;
  border-radius: 0.5rem;
  border: 2px solid var(--color-light);
  transition: all 0.3s ease-in-out;
  background-color: var(--color-bg);
}

input.input[type='text']:focus,
input.input[type='email']:focus,
input.input[type='password']:focus,
input.input[type='number']:focus,
input.input[type='text']:active,
input.input[type='email']:active,
input.input[type='password']:active,
input.input[type='number']:active{
  outline: none;
  border: 2px solid var(--color-main);
}
</style>

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>Enter new password</h3>

            <p>
                Please enter your new password twice so we can verify you typed it in correctly.
            </p>
            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                {{form.as_p}}       
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Change my password" />
            </form>
        </div>
    </div>
</main>

{% endblock  %}

templates/password_reset_sent.html
{% extends 'main.html' %}
{% block content %}
<style>
input.input[type='text'],
input.input[type='email'],
input.input[type='password'],
input.input[type='number'],
select.input,
textarea.input {
  min-width: 24rem;
  width: 100%;
  padding: 1.2rem 1.5rem;
  border-radius: 0.5rem;
  border: 2px solid var(--color-light);
  transition: all 0.3s ease-in-out;
  background-color: var(--color-bg);
}

input.input[type='text']:focus,
input.input[type='email']:focus,
input.input[type='password']:focus,
input.input[type='number']:focus,
input.input[type='text']:active,
input.input[type='email']:active,
input.input[type='password']:active,
input.input[type='number']:active{
  outline: none;
  border: 2px solid var(--color-main);
}
</style>

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <h3>Password reset sent</h3>

            <p>
                We've emailed you instructions for setting your password,
                if an account exists with the email you entered. You should receive them short
            </p>
            <br>
            <p>
                If you don't receive an email, please make sure you've entered the address you check your spam folder.
            </p>
            
        </div>
    </div>
</main>

{% endblock  %}